version: '3.9'

services:
  database:
    image: mysql:8
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend
  service-monitoring:
    build:
      context: ./service-monitoring
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://database:3306/dev
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=secret
    depends_on:
      - database
    networks:
      - backend
  ui-monitoring:
    build:
      context: ./ui-monitoring
    ports:
      - "8090:80"

networks:
  backend:
